version: '3.1'
services:
  db:
    image: postgres:14
    container_name: contenedor
    environment:
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: luis
      POSTGRES_DB: examen
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin
    container_name: pgadmin
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2024.luis_montiel@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: luis123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: