services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: luis
      POSTGRES_DB: examen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 2024_luis.montiel@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: luis123
    ports:
      - "5050:80"

volumes:
  postgres_data:
